version: 2.1

orbs:
  android: circleci/android@2.3.0
jobs:
  test:
    description: Runs unit tests and instrumented tests on the Survey app
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1

    steps:
      - checkout
      - run:
          name: Install OpenJDK 8
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"' >> $BASH_ENV
            java -version
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - run:
          name: Update Package list
          command: sudo apt-get update
      - run:
          name: Install the latest Android SDK
          command: |
            sdkmanager --update
            sdkmanager --list
      - android/create-avd:
          avd-name: customavd
          install: true
          system-image: system-images;android-30;default;x86_64
          additional-args: --sdcard 2048M

      - android/start-emulator:
          avd-name: customavd
          no-window: true
          restore-gradle-cache-prefix: v1
          post-emulator-launch-assemble-command: ./gradlew assemble

      - run:
          name: show package name
          command: adb shell pm list packages

      - android/run-tests:
          test-command: ./gradlew test

      - android/run-tests:
          test-command: ./gradlew connectedAndroidTest
      - android/save-gradle-cache:
          cache-prefix: v1

      - store_artifacts:
          name: Store Test Results
          path: survey_app/build/outputs/androidTest-results
      - store_artifacts:
          name: Store Test Reports
          path: tables_app/build/reports

  build:
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - run:
          name: Install OpenJDK 8
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"' >> $BASH_ENV
            java -version

      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - android/restore-gradle-cache:
          cache-prefix: v1

      - run:
          name: Echo JAVA HOME
          command: |
            echo $JAVA_HOME  

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache:
          cache-prefix: v1
      - run:
          name: Build Survey
          command: ./gradlew assemble

      - store_artifacts:
          name: Store Build Artifacts
          path: survey_app/build/outputs/apk


workflows:
  build-test-deploy-workflow:
    jobs:
      - build
      - test:
          requires:
            - build

